### ISSUE TITLE
[dev.icinga.com #11725] PNP preview w/out module permission

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-pnp#23]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11725

**Created by Anonymous on 2016-05-04 08:42:04 +00:00**

Assignee: _Anonymous_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2017-01-02 16:20:58 +00:00 (in Redmine)_

---

Hi All,
I just noticed, that if a user has not the permission to access the pnp module, he nevertheless gets the username/password field for PNP and the "small graphs preview" shown in Host/Service details.
IMHO the preview also shouldn't be shown, so for the user w/out the pnp module permission it seems as same as the module is not activated at all.
Just now we have the problem, that the credentials field pops up every time we go to a host/service detail.

Regards,

Amo

**Attachments**

* [1.JPG](https://dev.icinga.com/attachments/download/3350/1.JPG) Anonymous - _2016-05-04 08:41:51 +00:00_
* [2.JPG](https://dev.icinga.com/attachments/download/3351/2.JPG) Anonymous - _2016-05-04 08:42:02 +00:00_

**Comment by dnsmichi** [comment]
Could be related to Icinga/icingaweb2#2686.

**Comment by MarcusCaepio** [comment]
Hi All, Bug is fixed! Just tested it. Issue can be closed.

Regards,
Marcus

**Comment by shakalandy** [comment]
@MarcusCaepio sure? for me it's not working with master.

**Comment by MarcusCaepio** [comment]
For me it is. Roles that don't have Access to the Module don't get a preview anymore

**Comment by shakalandy** [comment]
Works for me now, was another issue in conflict with this change.

**Comment by lazyfrosch** [comment]
Closing this
