### ISSUE TITLE
Icingaweb2 service page not showing pnp thumbnail

### ISSUE THREAD

**Issue by totoroliu** [Icinga/icingaweb2-module-pnp#32]
## Expected Behavior

From IcingaWeb2 service page,
I'm expecting to see 5 thumbnails for "one year", "one month", "one week", "25 hours", "4 hours":
https://github.com/Icinga/icingaweb2-module-pnp/blob/master/doc/screenshot/detail_view.png?raw=true

## Current Behavior

I don't see any of thumbnails existed under the service page.

But I do see there are 3 "action" links within "Actions" section and above "inspect" linke :
Action 1: http://192.168.100.71/pnp4nagios/graph?host=rick-tftp&srv=check_ping (graph working)
Action 2: http://192.168.100.71/class='tips (page not found)
Action 3: http://192.168.100.71/rel='/pnp4nagios/popup?host=rick-tftp&srv=check_ping (page not found)
The "Action 1" link will open pnp4nagios page with graph.

These 3 "action" links behave the same as my old system,
where 5 thumbnails displayed.

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Clean Ubuntu 16.04 installation
2. Setup/Configure Icinga2 and IcingaWeb2
3. Refer to this https://tipstricks.itmatrix.eu/installing-icinga2-in-debian-wheezy/  for pnp4nagios configuration
4.

## Context

I had an old installation of:
* Ubuntu 14.04.5
* Icinga 2.5.4-1~ppa1~trusty2
* apache2 2.4.7-1ubuntu4.16
* php5 5.5.9+dfsg-1ubuntu4.21
* Icingaweb2 2.4.1-1~ppa1404+1
* IcingaWeb2 loaded modules:
doc 2.4.1
monitoring 2.4.1
pnp  1.0.1
* pnp4nagios 0.6.16-2 (from apt-get)

The service page had those thumbnails displayed successfully.

## Your Environment

* Ubuntu 16.04.4
* Icinga2 2.8.4-1.xenial
* Apache2 v2.4.18-2ubuntu3.9
* php 1:7.0+35ubuntu6.1
* php7.0 7.0.30-0ubuntu0.16.04.1
* IcingaWeb2 v2.5.3
* IcingaWeb2 loaded modules:
director  1.4.3
doc 2.5.3
monitoring 2.5.3
pnp  1.1.0 (git-hash: 6377405e7b0f9f01b441a38ca63f2c9adaef3f5e)
* pnp4nagios-0.6.26 (make from source tarball)

**Comment by joseph-holland** [comment]
Hi @totoroliu,
Not sure if you've fixed this already, but I had the same issue on Debian 9 following basically the same tutorials.
I've found that once you've enabled the pnp module in IcingaWeb2 you need to ensure that the 'PNP4Nagios configuration' directory is set correctly.  See my config.ini below:
'''
[pnp4nagios]
config_dir = "/usr/local/pnp4nagios/etc/"
base_url = "/pnp4nagios"
menu_disabled = "1"
default_query = "host=.pnp-internal&srv=runtime"
'''

Once I set this the thumbnails and graphs started to appear.

Joe

**Comment by totoroliu** [comment]
No, I haven't had the fix yet~

What's correct configuration directory?
Where should it point to?


Below is my "`/etc/icingaweb2/modules/pnp/config.ini`" on Ubuntu 16.04:
```
[pnp4nagios]
config_dir = "/usr/share/icingaweb2/modules/pnp"
base_url = "/pnp4nagios"
menu_disabled = "0"
default_query = "host=.pnp-internal&srv=runtime"
```

```
$ ls -l /usr/share/icingaweb2/modules/pnp
total 60
drwxr-xr-x 6 root root  4096 Jul  8 18:51 application
-rw-r--r-- 1 root root   352 Jul  8 18:51 AUTHORS
-rw-r--r-- 1 root root   788 Jul  8 18:51 CHANGELOG.md
-rw-r--r-- 1 root root   544 Jul  8 18:51 configuration.php
-rw-r--r-- 1 root root   521 Jul  8 18:51 icingaexchange.yml
drwxr-xr-x 3 root root  4096 Jul  8 18:51 library
-rw-r--r-- 1 root root 18091 Jul  8 18:51 LICENSE
-rw-r--r-- 1 root root   330 Jul  8 18:51 module.info
-rw-r--r-- 1 root root  1083 Jul  8 18:51 README.md
-rw-r--r-- 1 root root  1017 Jul  8 18:51 RELEASE.md
-rw-r--r-- 1 root root    38 Jul  8 18:51 run.php
```

**Comment by totoroliu** [comment]
I have also tried to change config_dir to "`/etc/icingaweb2/modules/pnp`":
```
[pnp4nagios]
config_dir = "/etc/icingaweb2/modules/pnp"
base_url = "/pnp4nagios"
menu_disabled = "0"
default_query = "host=.pnp-internal&srv=runtime"
```    

But this doesn't work either.
(I have also restarted Apache2 and Icgina2 services between the changes).

**Comment by totoroliu** [comment]
oh After using the same config_dir as yours,
everything is working now.
Thanks you a lot @joseph-holland 


```
$ cat /etc/icingaweb2/modules/pnp/config.ini 
[pnp4nagios]
config_dir = "/usr/local/pnp4nagios/etc"
base_url = "/pnp4nagios"
menu_disabled = "0"
default_query = "host=.pnp-internal&srv=runtime"
```

**Comment by joseph-holland** [comment]
Yep, as stated in Issue #18, if you comment out the view statements in the config_local.php file, this fixes the double thumbnails.

`vim /usr/local/pnp4nagios/etc/config_local.php`

Comment out the view statements from around lines 214:
```
#
# Define default views with title and start timerange in seconds
#
# remarks: required escape on " with backslash
#
#$views[] = array('title' => 'One Hour',  'start' => (60*60) );
#$views[] = array('title' => '4 Hours',   'start' => (60*60*4) );
#$views[] = array('title' => '25 Hours',  'start' => (60*60*25) );
#$views[] = array('title' => 'One Week',  'start' => (60*60*25*7) );
#$views[] = array('title' => 'One Month', 'start' => (60*60*24*32) );
#$views[] = array('title' => 'One Year',  'start' => (60*60*24*380) );
```

**Comment by lazyfrosch** [comment]
I guess this issue is resolved
