### ISSUE TITLE
pnp module for icingaweb2 does not work anymore after a package update (no more graphs in icingaweb2)

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2-module-pnp#44]
pnp module for icingaweb2 does not work anymore after a package update (no more graphs in icingaweb2)

## Current Behavior
Fter updateing the following packages, pnp module for icingaweb2 does not work anymore after a package update (no more graphs in icingaweb2)
icinga-php-library (0.10.0-1+ubuntu20.04) ...
icingadb-web (1.0.1-1+ubuntu20.04) ...

Note that I've modified the module.info with Depends: icingadb (>=1.0.0) to make it pass the dependency checks when having icingadb enabled and monitoring module disabled.

## Steps to Reproduce (for bugs)

1. update to icinga-php-library (0.10.0-1+ubuntu20.04) and icingadb-web (1.0.1-1+ubuntu20.04) ...
2. check if there are still the graphs in icingaweb2 in service or host detailed view
3.
4.

## Your Environment

* Module version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by nilmerg** [comment]
Hi,

you may try to apply this to Icinga DB Web: https://github.com/Icinga/icingadb-web/pull/639

It should solve your problem for now.

**Comment by Tontonitch** [comment]
Great, thanks @nilmerg !
It fixes the issue.

**Comment by nilmerg** [comment]
Fine! I'll close here then.
